sudo: true
language: cpp
os:
- osx
compiler:
- gcc
cache:
  directories:
    - "$HOME/Library/Caches/Homebrew"
script:
- pushd ..
- git clone https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction
- pushd ITKMinimalPathExtraction
- /Users/Kitware/Dashboards/ITK/ITKPythonPackage/scripts/macpython-build-module-wheels.sh 3.6
- popd; popd
- /Users/Kitware/Dashboards/ITK/ITKPythonPackage/scripts/macpython-build-module-wheels.sh 3.6
- tar -zcvf dist.tar.gz dist/
- curl --upload-file dist.tar.gz https://transfer.sh/dist.tar.gz
